// AUTO-GENERATED by `setup sync` — do not edit by hand.
import React from "react";

import * as mod_0_hydrology_module from "@modules/hello";

export const moduleRoutes: { path: string; Component: React.ComponentType }[] = [...mod_0_hydrology_module.routes];
export const moduleNavItems: { label: string; to: string }[] = [...mod_0_hydrology_module.navItems];
