# alembic.ini — TEMPLATE
#
# backend/alembic.ini is auto-generated by `setup sync` and is gitignored.
# This template is the committed source of truth.
#
# `setup sync` reads modules.lock.yaml and writes:
#   version_locations = alembic/versions <module1-versions-abs-path> ...
#
# To regenerate:  cd <core-root> && python -m setup_cli sync
#
[alembic]
script_location = alembic
prepend_sys_path = .
# `version_locations` (added by `setup sync`) holds several space-separated
# paths; this tells Alembic how to split them (its default is "no split",
# which would treat the whole string as one path).
path_separator = space
sqlalchemy.url =

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
