import { reactConfig } from "@packages/eslint-config";

/**
 * ESLint 9 flat config for the web app.
 * @see https://eslint.org/docs/latest/use/configure/configuration-files
 *
 * @type {import("eslint").Linter.Config[]}
 */
export default [
  {
    name: "web/ignores",
    ignores: [
      // Generated by `setup sync` — do not lint.
      "src/module-registry.generated.ts",
      "src/modules.generated.ts",
    ],
  },
  ...reactConfig,
  {
    name: "web/imports",
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["../*"],
              message: "Prefer absolute imports using @/ alias",
            },
          ],
        },
      ],
    },
  },
];
