"""
Alembic Migration Environment (async SQLAlchemy)

Run via the `migrate` compose service:  alembic upgrade heads

- The database URL comes from app settings (`alembic.ini` leaves it empty).
- PostGIS + pgvector are ensured before any migration runs.
- Installed modules' models & migration dirs are discovered from
  `modules.lock.yaml` so `upgrade head` covers module tables too.
- PostGIS-internal objects are excluded so autogenerated migrations never
  try to drop/alter them.
"""
from __future__ import annotations

import asyncio
import importlib
import os
import sys
from logging.config import fileConfig
from pathlib import Path

import yaml
from alembic import context
from sqlalchemy import pool, text
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# ── Make the app package importable ──────────────────────────────────────────
BACKEND_DIR = Path(__file__).resolve().parents[1]
ROOT = BACKEND_DIR.parent  # core/
sys.path.insert(0, str(BACKEND_DIR))

from app.core.config import get_settings
from app.core.db import Base

# ── Core models (register everything on Base.metadata) ───────────────────────
import app.api.auth.models            # noqa: F401
import app.api.data.models            # noqa: F401
import app.api.projects.models        # noqa: F401
import app.api.maps.models            # noqa: F401
import app.api.maps.share.models      # noqa: F401
import app.api.notifications.models   # noqa: F401
import app.api.profile.models         # noqa: F401

# ── Dynamically discover installed modules ────────────────────────────────────
# Note: the *version search path* (version_locations) lives in the generated
# `alembic.ini` (written by `setup sync`); it must be known before Alembic
# builds its script directory, so it cannot be set from here. This block only
# imports module ORM models so `target_metadata` is complete (autogenerate).
#
# Set ALEMBIC_CORE_ONLY=1 to exclude module models — used when (re)generating
# the *core* initial migration so module tables stay owned by the modules'
# own migration branches (see modules/<name>-module/backend/alembic/).
_lock_file = ROOT / "modules.lock.yaml"
_core_only = os.environ.get("ALEMBIC_CORE_ONLY") == "1"

if _lock_file.exists() and not _core_only:
    _lock = yaml.safe_load(_lock_file.read_text()) or {}
    for _mod in _lock.get("selected", []):
        _mod_path = ROOT / _mod["path"]
        _meta_path = _mod_path / "module.yaml"
        if not _meta_path.exists():
            continue
        _backend = (yaml.safe_load(_meta_path.read_text()) or {}).get("backend")
        if not _backend:
            continue

        # Inject the module backend dir so its models import cleanly.
        _backend_dir = str(_mod_path / "backend")
        if _backend_dir not in sys.path:
            sys.path.insert(0, _backend_dir)

        if _backend.get("models_attr"):
            try:
                importlib.import_module(f'{_backend["package"]}.{_backend["models_attr"]}')
            except Exception as _exc:  # noqa: BLE001 — keep the migration running
                print(f"WARNING: could not import module models '{_backend['package']}': {_exc}")

# ── Alembic config ────────────────────────────────────────────────────────────
config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The database URL comes from app settings, not from alembic.ini.
config.set_main_option("sqlalchemy.url", get_settings().database_url)

target_metadata = Base.metadata


# ── PostGIS / pgvector internals Alembic must never touch ─────────────────────
# PostGIS installs a fixed set of internal tables in its own schemas (tiger,
# tiger_data, topology). alembic 1.19 + SQLAlchemy 2.x can reflect them with
# schema=None (flattened), so we filter by name in addition to schema.
EXCLUDED_SCHEMAS = {"tiger", "tiger_data", "topology"}
EXCLUDED_TABLES = {
    # core extension tables (public schema)
    "spatial_ref_sys",
    "geometry_columns",
    "geography_columns",
    "raster_columns",
    "raster_overviews",
    # tiger geocoder tables
    "addr",
    "addrfeat",
    "bg",
    "county",
    "county_lookup",
    "countysub_lookup",
    "cousub",
    "direction_lookup",
    "edges",
    "faces",
    "featnames",
    "geocode_settings",
    "geocode_settings_default",
    "loader_lookuptables",
    "loader_platform",
    "loader_variables",
    "pagc_gaz",
    "pagc_lex",
    "pagc_rules",
    "place",
    "place_lookup",
    "secondary_unit_lookup",
    "state",
    "state_lookup",
    "street_type_lookup",
    "tabblock",
    "tabblock20",
    "tract",
    "zcta5",
    "zip_lookup",
    "zip_lookup_all",
    "zip_lookup_base",
    "zip_state",
    "zip_state_loc",
    # topology extension tables
    "layer",
    "topology",
}


def include_object(object, name, type_, reflected, compare_to):
    """Keep autogenerated migrations away from PostGIS-internal objects."""
    if type_ == "table":
        if getattr(object, "schema", None) in EXCLUDED_SCHEMAS:
            return False
        if name in EXCLUDED_TABLES:
            return False

    if type_ == "index" and getattr(object, "table", None) is not None:
        table = object.table
        if getattr(table, "schema", None) in EXCLUDED_SCHEMAS:
            return False
        if table.name in EXCLUDED_TABLES:
            return False

    return True


def include_name(name, type_, parent_names):
    """Name-level filter: skip PostGIS-internal schemas and tables.

    alembic 1.19 may flatten non-default schemas (schema_name=None), so the
    table-name check is the reliable guard."""
    if type_ == "schema":
        return name not in EXCLUDED_SCHEMAS
    if type_ == "table":
        return name not in EXCLUDED_TABLES
    return True


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode — generates SQL without connecting."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        include_name=include_name,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,
        include_name=include_name,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        # Ensure PostGIS and pgvector exist BEFORE any migration runs
        # (idempotent — covers fresh and pre-existing databases).
        await connection.execute(text("CREATE EXTENSION IF NOT EXISTS postgis"))
        await connection.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))
        await connection.commit()

        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
