"""Initial core schema

Revision ID: 92d68d0451ec
Revises: 
Create Date: 2026-08-23 15:04:01.499329
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '92d68d0451ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('crs', sa.String(length=128), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=512), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_datasets_name'), 'geo_datasets', ['name'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_table('notification_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_messages_category'), 'notification_messages', ['category'], unique=False)
    op.create_index(op.f('ix_notification_messages_created_at'), 'notification_messages', ['created_at'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('accent_color', sa.String(length=20), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('geo_features',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['geo_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_features_dataset_id'), 'geo_features', ['dataset_id'], unique=False)
    op.create_table('group_permissions',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('preferred_timezone', sa.String(length=64), nullable=True),
    sa.Column('primary_organization_id', sa.String(length=36), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['primary_organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_primary_organization_id'), 'users', ['primary_organization_id'], unique=False)
    op.create_table('access_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_role', sa.String(length=20), nullable=False),
    sa.Column('granted_role', sa.String(length=20), nullable=True),
    sa.Column('approval_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'user_id', name='uq_access_request')
    )
    op.create_index(op.f('ix_access_requests_approval_token'), 'access_requests', ['approval_token'], unique=True)
    op.create_index(op.f('ix_access_requests_entity_id'), 'access_requests', ['entity_id'], unique=False)
    op.create_index(op.f('ix_access_requests_entity_type'), 'access_requests', ['entity_type'], unique=False)
    op.create_index(op.f('ix_access_requests_user_id'), 'access_requests', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('toasts', sa.Boolean(), nullable=False),
    sa.Column('sound', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notification_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['notification_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_notification_delivered')
    )
    op.create_index(op.f('ix_notification_recipients_message_id'), 'notification_recipients', ['message_id'], unique=False)
    op.create_index('ix_notification_recipients_unread', 'notification_recipients', ['user_id', 'read'], unique=False)
    op.create_index(op.f('ix_notification_recipients_user_id'), 'notification_recipients', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('zoom', sa.Float(), nullable=False),
    sa.Column('basemap', sa.String(length=100), nullable=False),
    sa.Column('layers_config', sa.JSON(), nullable=False),
    sa.Column('annotations', sa.JSON(), nullable=False),
    sa.Column('bookmarks', sa.JSON(), nullable=False),
    sa.Column('comments', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('share_link_role', sa.String(length=20), nullable=False),
    sa.Column('share_link_enabled', sa.Boolean(), nullable=False),
    sa.Column('share_settings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_share_token'), 'projects', ['share_token'], unique=True)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_table('user_groups',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('user_organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_org_membership')
    )
    op.create_index(op.f('ix_user_organizations_organization_id'), 'user_organizations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_organizations_user_id'), 'user_organizations', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('theme_mode', sa.String(length=16), nullable=False),
    sa.Column('map_units', sa.String(length=16), nullable=False),
    sa.Column('default_basemap', sa.String(length=64), nullable=True),
    sa.Column('accent_color', sa.String(length=20), nullable=True),
    sa.Column('compact_mode', sa.Boolean(), nullable=False),
    sa.Column('font_scale', sa.String(length=12), nullable=False),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('maps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('zoom', sa.Float(), nullable=False),
    sa.Column('bearing', sa.Float(), nullable=False),
    sa.Column('pitch', sa.Float(), nullable=False),
    sa.Column('basemap', sa.String(length=100), nullable=False),
    sa.Column('layers_config', sa.JSON(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('widgets_config', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('share_link_role', sa.String(length=20), nullable=False),
    sa.Column('share_link_enabled', sa.Boolean(), nullable=False),
    sa.Column('share_settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maps_is_public'), 'maps', ['is_public'], unique=False)
    op.create_index(op.f('ix_maps_owner_id'), 'maps', ['owner_id'], unique=False)
    op.create_index(op.f('ix_maps_project_id'), 'maps', ['project_id'], unique=False)
    op.create_index(op.f('ix_maps_share_token'), 'maps', ['share_token'], unique=True)
    op.create_index(op.f('ix_maps_title'), 'maps', ['title'], unique=False)
    op.create_table('project_group_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'group_id', name='uq_project_group_access')
    )
    op.create_index(op.f('ix_project_group_access_group_id'), 'project_group_access', ['group_id'], unique=False)
    op.create_index(op.f('ix_project_group_access_project_id'), 'project_group_access', ['project_id'], unique=False)
    op.create_table('project_user_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('invited_by_id', sa.String(length=36), nullable=True),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user_access')
    )
    op.create_index(op.f('ix_project_user_access_email'), 'project_user_access', ['email'], unique=False)
    op.create_index(op.f('ix_project_user_access_project_id'), 'project_user_access', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_user_access_user_id'), 'project_user_access', ['user_id'], unique=False)
    op.create_table('map_group_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('map_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_id', 'group_id', name='uq_map_group_access')
    )
    op.create_index(op.f('ix_map_group_access_group_id'), 'map_group_access', ['group_id'], unique=False)
    op.create_index(op.f('ix_map_group_access_map_id'), 'map_group_access', ['map_id'], unique=False)
    op.create_table('map_user_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('map_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('invited_by_id', sa.String(length=36), nullable=True),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_id', 'user_id', name='uq_map_user_access')
    )
    op.create_index(op.f('ix_map_user_access_email'), 'map_user_access', ['email'], unique=False)
    op.create_index(op.f('ix_map_user_access_invite_token'), 'map_user_access', ['invite_token'], unique=True)
    op.create_index(op.f('ix_map_user_access_map_id'), 'map_user_access', ['map_id'], unique=False)
    op.create_index(op.f('ix_map_user_access_user_id'), 'map_user_access', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_map_user_access_user_id'), table_name='map_user_access')
    op.drop_index(op.f('ix_map_user_access_map_id'), table_name='map_user_access')
    op.drop_index(op.f('ix_map_user_access_invite_token'), table_name='map_user_access')
    op.drop_index(op.f('ix_map_user_access_email'), table_name='map_user_access')
    op.drop_table('map_user_access')
    op.drop_index(op.f('ix_map_group_access_map_id'), table_name='map_group_access')
    op.drop_index(op.f('ix_map_group_access_group_id'), table_name='map_group_access')
    op.drop_table('map_group_access')
    op.drop_index(op.f('ix_project_user_access_user_id'), table_name='project_user_access')
    op.drop_index(op.f('ix_project_user_access_project_id'), table_name='project_user_access')
    op.drop_index(op.f('ix_project_user_access_email'), table_name='project_user_access')
    op.drop_table('project_user_access')
    op.drop_index(op.f('ix_project_group_access_project_id'), table_name='project_group_access')
    op.drop_index(op.f('ix_project_group_access_group_id'), table_name='project_group_access')
    op.drop_table('project_group_access')
    op.drop_index(op.f('ix_maps_title'), table_name='maps')
    op.drop_index(op.f('ix_maps_share_token'), table_name='maps')
    op.drop_index(op.f('ix_maps_project_id'), table_name='maps')
    op.drop_index(op.f('ix_maps_owner_id'), table_name='maps')
    op.drop_index(op.f('ix_maps_is_public'), table_name='maps')
    op.drop_table('maps')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_organizations_user_id'), table_name='user_organizations')
    op.drop_index(op.f('ix_user_organizations_organization_id'), table_name='user_organizations')
    op.drop_table('user_organizations')
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_share_token'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notification_recipients_user_id'), table_name='notification_recipients')
    op.drop_index('ix_notification_recipients_unread', table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_message_id'), table_name='notification_recipients')
    op.drop_table('notification_recipients')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_access_requests_user_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_entity_type'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_entity_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_approval_token'), table_name='access_requests')
    op.drop_table('access_requests')
    op.drop_index(op.f('ix_users_primary_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('group_permissions')
    op.drop_index(op.f('ix_geo_features_dataset_id'), table_name='geo_features')
    op.drop_table('geo_features')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_notification_messages_created_at'), table_name='notification_messages')
    op.drop_index(op.f('ix_notification_messages_category'), table_name='notification_messages')
    op.drop_table('notification_messages')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_geo_datasets_name'), table_name='geo_datasets')
    op.drop_table('geo_datasets')
    # ### end Alembic commands ###
