from .registry import ROOT, load_module_meta

GENERATED_FILE = ROOT / "frontend" / "apps" / "web" / "src" / "modules.generated.ts"


def generate_frontend_routes(lock: dict) -> None:
    imports, route_spreads, nav_spreads = [], [], []

    for i, mod in enumerate(lock["selected"]):
        meta = load_module_meta(mod["name"])
        fe_cfg = meta.get("frontend")
        if not fe_cfg:
            continue
        alias = f"mod_{i}_{mod['name']}".replace("-", "_")
        imports.append(f'import * as {alias} from "{fe_cfg["package_name"]}";')
        route_spreads.append(f"...{alias}.routes")
        nav_spreads.append(f"...{alias}.navItems")

    content = "// AUTO-GENERATED by `setup sync` — do not edit by hand.\n"
    content += "import React from \"react\";\n\n"
    if imports:
        content += "\n".join(imports) + "\n\n"
    content += f"export const moduleRoutes: {{ path: string; Component: React.ComponentType }}[] = [{', '.join(route_spreads)}];\n"
    content += f"export const moduleNavItems: {{ label: string; to: string }}[] = [{', '.join(nav_spreads)}];\n"
    GENERATED_FILE.write_text(content)