"""
Codegen — generates the dynamic module registry for the frontend shell.

OLD approach (static imports, hardcoded in bundle):
  import * as mod from "@modules/hello";
  export const moduleRoutes = [...mod.routes];

NEW approach (lazy registry — routes activated by /api/modules at runtime):
  export const moduleRegistry = {
    "hydrology-module": () => import("@modules/hydrology"),
  };

The App shell fetches /api/modules, checks enabled modules, and only mounts
routes for modules that are both in the registry AND enabled server-side.
"""
from .registry import ROOT, load_module_meta

GENERATED_FILE = (
    ROOT / "frontend" / "apps" / "web" / "src" / "module-registry.generated.ts"
)

# Old file (static import approach) — kept for backwards compat but no longer imported
_OLD_FILE = ROOT / "frontend" / "apps" / "web" / "src" / "modules.generated.ts"


def generate_frontend_routes(lock: dict) -> None:
    entries: list[str] = []

    for mod in lock.get("selected", []):
        meta = load_module_meta(mod["name"])
        fe_cfg = meta.get("frontend")
        if not fe_cfg:
            continue
        package = fe_cfg["package_name"]
        name = mod["name"]
        # Each entry: "module-name": () => import("@modules/pkg")
        entries.append(f'  "{name}": () => import("{package}"),')

    lines: list[str] = [
        "// AUTO-GENERATED by `setup sync` — do not edit by hand.",
        "// Add/remove modules via modules.registry.yaml + modules.lock.yaml.",
        "",
        "import type { ComponentType } from \"react\";",
        "",
        "/** Shape each module package must export. */",
        "export interface ModuleBundle {",
        "  /** Root page component for this module. */",
        "  Page: ComponentType;",
        "  /** URL path this module mounts at (e.g. \"/hydrology\"). */",
        "  routePath: string;",
        "  /** Top-nav entry for this module. */",
        "  navItem: { label: string; to: string };",
        "}",
        "",
        "/**",
        " * Registry of all *installed* module loaders.",
        " * Keyed by the module name in modules.lock.yaml.",
        " *",
        " * The shell uses /api/modules to decide which entries to activate at runtime.",
        " * Only modules present here AND enabled server-side will be mounted.",
        " */",
        "export const moduleRegistry: Record<string, () => Promise<ModuleBundle>> = {",
        *entries,
        "};",
        "",
    ]

    GENERATED_FILE.write_text("\n".join(lines))

    # Write a tombstone so developers know the old file is superseded
    if _OLD_FILE.exists():
        _OLD_FILE.write_text(
            "// SUPERSEDED — module routing is now handled by module-registry.generated.ts\n"
            "// This file is kept only so existing imports don't break during migration.\n"
            "export const moduleRoutes: never[] = [];\n"
            "export const moduleNavItems: never[] = [];\n"
        )